apiVersion: v1
kind: Service
metadata:
  name: servicio-eureka-server  
spec:
  selector:                  
    deploymentconfig: simple-webapp-docker
  ports:
  - name: 8761-tcp
    port: 8761               
    protocol: TCP
    targetPort: 8761 